#To edit
# {name_1} name of this instance
# {host} public hostname
# {entrypoint} a valid entrypoint 
# /!\ only 1 dind per entrypoint
# Tessted on: - traefik 2.0.2

version: '3.8'

networks:
  internet:
    external: true
    name: base_external

services:
  dind-{name_1}:
    image: docker:dind
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - internet
    entrypoint: sh -c  '
      apk update > /dev/null;
      apk upgrade > /dev/null;
      apk add bash > /dev/null;
      apk add openssh > /dev/null;
      t=$$(cat /dev/urandom | tr -dc "a-zA-Z0-9" | fold -w 12 | head -n 1);
      echo -e "$$t\n$$t" | passwd > /dev/null;
      echo "ChallengeResponseAuthentication yes" >> /etc/ssh/sshd_config;
      echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config;
      echo "PermitRootLogin yes" >> /etc/ssh/sshd_config;
      echo "AllowTcpForwarding yes" >> /etc/ssh/sshd_config;
      ssh-keygen -A > /dev/null;
      $$(which sshd) > /dev/null;
      echo -e $$t;
      sh'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=base_external"
        - "traefik.http.routers.{name_1}.rule=Host(`test.{host}`)"
        - "traefik.http.routers.{name_1}.tls.certresolver=le"
        - "traefik.http.routers.{name_1}.entrypoints=websecure,web"
        - "traefik.http.services.{name_1}.loadbalancer.passhostheader=true"
        - "traefik.http.services.{name_1}.loadbalancer.server.port=8080"
        - "traefik.tcp.routers.{name_1}-ssh.rule=HostSNI(`*`)"
        - "traefik.tcp.routers.{name_1}-ssh.entrypoints={entrypoint}"
        - "traefik.tcp.routers.{name_1}-ssh.service={name_1}-ssh-svc"
        - "traefik.tcp.services.{name_1}-ssh-svc.loadbalancer.server.port=22"
