version: "3.8"

networks:
  sync:
    driver: overlay
    driver_opts:
      encrypted: ""
    internal: true

services:
  syncthing:
    image: ghcr.io/linuxserver/syncthing
    tty: true
    entrypoint: ash -c  '
      apk update ;
      apk upgrade ;
      apk add curl ;
      apk add jq ;
      apk add libxml2-utils ;
      truncate -s-3 init;
      ./init &
      sleep 40;
      curl -X GET http://127.0.0.1:8384 > /dev/null ;
      id=$$(cat /config/config.xml | grep "<device id=" | tail -n 1 | cut -d\" -f2);
      n=$$(cat /config/config.xml | grep "<device id=" | tail -n 1 | cut -d\" -f2 | head -c 5);
      t=$$(cat /config/csrftokens.txt | tail -n 1);
      while true; do
        d=$$(curl -X GET -H "X-CSRF-Token-$$n:$$t" http://127.0.0.1:8384/rest/system/discovery | jq -r "keys[]");
        echo  "<configuration version=\"32\"><folder id=\"default\" label=\"Default Folder\" path=\"/config/Sync\" type=\"sendreceive\" rescanIntervalS=\"5\" fsWatcherEnabled=\"true\" fsWatcherDelayS=\"10\" ignorePerms=\"false\" autoNormalize=\"true\"> <filesystemType>basic</filesystemType><device id=\"$$id\" introducedBy=\"\"> <encryptionPassword></encryptionPassword> </device>" > testconf ;
        for i in $$d; do
          echo "<device id=\"$$i\" introducedBy=\"\"> <encryptionPassword></encryptionPassword> </device>" >> testconf ;
        done ;
        echo "<minDiskFree unit=\"\">0</minDiskFree> <versioning> <cleanupIntervalS>0</cleanupIntervalS> </versioning> <copiers>0</copiers> <pullerMaxPendingKiB>0</pullerMaxPendingKiB> <hashers>0</hashers> <order>random</order> <ignoreDelete>false</ignoreDelete> <scanProgressIntervalS>0</scanProgressIntervalS> <pullerPauseS>0</pullerPauseS> <maxConflicts>-1</maxConflicts> <disableSparseFiles>false</disableSparseFiles> <disableTempIndexes>false</disableTempIndexes> <paused>false</paused> <weakHashThresholdPct>25</weakHashThresholdPct> <markerName>.stfolder</markerName> <copyOwnershipFromParent>false</copyOwnershipFromParent> <modTimeWindowS>0</modTimeWindowS> <maxConcurrentWrites>2</maxConcurrentWrites> <disableFsync>false</disableFsync> <blockPullOrder>standard</blockPullOrder> <copyRangeMethod>standard</copyRangeMethod> <caseSensitiveFS>false</caseSensitiveFS> <junctionsAsDirs>false</junctionsAsDirs> </folder> <device id=\"$$id\" name=\"syncthing\" compression=\"metadata\" introducer=\"false\" skipIntroductionRemovals=\"false\" introducedBy=\"\"> <address>dynamic</address> <paused>false</paused> <autoAcceptFolders>false</autoAcceptFolders> <maxSendKbps>0</maxSendKbps> <maxRecvKbps>0</maxRecvKbps> <maxRequestKiB>0</maxRequestKiB> <untrusted>false</untrusted> </device>" >> testconf ;
        for i in $$d; do
          echo "<device id=\"$$i\" name=\"syncthing2\" compression=\"metadata\" introducer=\"false\" skipIntroductionRemovals=\"false\" introducedBy=\"\"> <address>dynamic</address> <paused>false</paused> <autoAcceptFolders>false</autoAcceptFolders> <maxSendKbps>0</maxSendKbps> <maxRecvKbps>0</maxRecvKbps> <maxRequestKiB>0</maxRequestKiB> <untrusted>false</untrusted> </device>" >> testconf ;
        done ;
        echo "<gui enabled=\"true\" tls=\"false\" debugging=\"false\"> <address>127.0.0.1:8384</address> <apikey>QqUT7mg4hdvRx5cLjkjpmcZnRRbyDYTd</apikey> <theme>default</theme> </gui> <ldap></ldap> <options> <listenAddress>default</listenAddress> <globalAnnounceServer>default</globalAnnounceServer> <globalAnnounceEnabled>true</globalAnnounceEnabled> <localAnnounceEnabled>true</localAnnounceEnabled> <localAnnouncePort>21027</localAnnouncePort> <localAnnounceMCAddr>[ff12::8384]:21027</localAnnounceMCAddr> <maxSendKbps>0</maxSendKbps> <maxRecvKbps>0</maxRecvKbps> <reconnectionIntervalS>60</reconnectionIntervalS> <relaysEnabled>true</relaysEnabled> <relayReconnectIntervalM>10</relayReconnectIntervalM> <startBrowser>true</startBrowser> <natEnabled>true</natEnabled> <natLeaseMinutes>60</natLeaseMinutes> <natRenewalMinutes>30</natRenewalMinutes> <natTimeoutSeconds>10</natTimeoutSeconds> <urAccepted>-1</urAccepted> <urSeen>3</urSeen> <urUniqueID></urUniqueID> <urURL>https://data.syncthing.net/newdata</urURL> <urPostInsecurely>false</urPostInsecurely> <urInitialDelayS>1800</urInitialDelayS> <restartOnWakeup>true</restartOnWakeup> <autoUpgradeIntervalH>12</autoUpgradeIntervalH> <upgradeToPreReleases>false</upgradeToPreReleases> <keepTemporariesH>24</keepTemporariesH> <cacheIgnoredFiles>false</cacheIgnoredFiles> <progressUpdateIntervalS>5</progressUpdateIntervalS> <limitBandwidthInLan>false</limitBandwidthInLan> <minHomeDiskFree unit=\"%\">1</minHomeDiskFree> <releasesURL>https://upgrades.syncthing.net/meta.json</releasesURL> <overwriteRemoteDeviceNamesOnConnect>false</overwriteRemoteDeviceNamesOnConnect> <tempIndexMinBlocks>10</tempIndexMinBlocks> <unackedNotificationID>authenticationUserAndPassword</unackedNotificationID> <trafficClass>0</trafficClass> <defaultFolderPath>~</defaultFolderPath> <setLowPriority>true</setLowPriority> <maxFolderConcurrency>0</maxFolderConcurrency> <crashReportingURL>https://crash.syncthing.net/newcrash</crashReportingURL> <crashReportingEnabled>true</crashReportingEnabled> <stunKeepaliveStartS>180</stunKeepaliveStartS> <stunKeepaliveMinS>20</stunKeepaliveMinS> <stunServer>default</stunServer> <databaseTuning>auto</databaseTuning> <maxConcurrentIncomingRequestKiB>0</maxConcurrentIncomingRequestKiB> <announceLANAddresses>true</announceLANAddresses> <sendFullIndexOnUpgrade>false</sendFullIndexOnUpgrade> </options> </configuration>" >> testconf ;
        echo -e "\n" >> /config/config.xml ;
        cat testconf | xmllint --format - | tail -n +2  > /config/config.xml ;
        curl -X POST -H "X-CSRF-Token-$$n:$$t" http://127.0.0.1:8384/rest/system/restart ;
        sleep 60;
      done'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ../sync_data:/config/Sync
    networks:
      - sync
    deploy:
      mode: global
